const Connection = require('../lib/connection.js');
const LaborApproval = require('../lib/laborApproval.js');

describe('Labor Approval Service', () => {
  let connection, laborApprovalSvc;

  beforeEach(() => {
    connection = new Connection({
      serverUrl: 'https://nowhere.com'
    });
    laborApprovalSvc = new LaborApproval(connection);
  });

  describe('approveTimesheet', () => {
    it('only approves the dates that have been supplied by the user', () => {
      const ds = {...sampleDataset()};
      ds.parameters.ds = ds.returnObj;

      const r = sinon.stub();
      r.withArgs('GetRows', sinon.match.any).returns(Promise.resolve(ds));
      r.withArgs('ApproveReject', sinon.match.any).returns(Promise.resolve(ds));

      laborApprovalSvc.makeRequest = r;

      return laborApprovalSvc
        .approveTimesheet(
          {
            FromDate: '2017-11-27',
            ToDate: '2017-11-28',
            EmployeeNum: 'TS'
          },
          {EmployeeNum: 'approver', Name: 'approver'},
          ['2017-11-27']
        )
        .then(result => {
          expect(r).to.have.been.calledWith('ApproveReject', {
            ipSalesRepCode: 'approver',
            ipAction: 'A',
            ipComment: '',
            ds: ds.returnObj
          });
        });
    });
  });
});

const sampleDataset = () => ({
  returnObj: {
    LaborDtl: [
      {
        Company: '700',
        EmployeeNum: 'TS',
        LaborHedSeq: 715627,
        LaborDtlSeq: 2179554,
        LaborType: 'P',
        LaborTypePseudo: 'P',
        ReWork: false,
        ReworkReasonCode: '',
        JobNum: 'L01094-L25',
        AssemblySeq: 0,
        OprSeq: 80,
        JCDept: 'RGELEPRD',
        ResourceGrpID: 'RGELEPRD',
        OpCode: 'OPELEASS',
        LaborHrs: 2,
        BurdenHrs: 2,
        LaborQty: 0,
        ScrapQty: 0,
        ScrapReasonCode: '',
        SetupPctComplete: 0,
        Complete: false,
        IndirectCode: '',
        LaborNote: 'Real time or bust?',
        ExpenseCode: 'MAIN',
        LaborCollection: false,
        AppliedToSchedule: false,
        ClockInMInute: 33702780,
        ClockOutMinute: 33702780,
        ClockInDate: '2017-11-27T00:00:00',
        ClockinTime: 17,
        ClockOutTime: 17,
        ActiveTrans: false,
        OverRidePayRate: 0,
        LaborRate: 0,
        BurdenRate: 20,
        DspClockInTime: '17:00',
        DspClockOutTime: '17:00',
        ResourceID: '',
        OpComplete: false,
        EarnedHrs: 0,
        AddedOper: false,
        PayrollDate: '2017-11-27T00:00:00',
        PostedToGL: false,
        FiscalYear: 0,
        FiscalPeriod: 0,
        JournalNum: 0,
        GLTrans: true,
        JournalCode: '',
        InspectionPending: false,
        CallNum: 0,
        CallLine: 0,
        ServNum: 0,
        ServCode: '',
        ResReasonCode: '',
        WipPosted: false,
        DiscrepQty: 0,
        DiscrpRsnCode: '',
        ParentLaborDtlSeq: 0,
        LaborEntryMethod: 'T',
        FiscalYearSuffix: '',
        FiscalCalendarID: '',
        BFLaborReq: false,
        ABTUID: '',
        ProjectID: '',
        PhaseID: '',
        RoleCd: '',
        TimeTypCd: '',
        PBInvNum: 0,
        PMUID: 0,
        TaskSetID: '',
        ApprovedDate: '2017-11-28T00:00:00',
        ClaimRef: '',
        QuickEntryCode: '',
        TimeStatus: 'E',
        CreatedBy: 'Timesheet',
        CreateDate: '2017-11-28T00:00:00',
        CreateTime: 58919,
        ChangedBy: 'Timesheet',
        ChangeDate: '2017-11-28T00:00:00',
        ChangeTime: 58919,
        ActiveTaskID: '',
        LastTaskID: '',
        CreatedViaTEWeekView: false,
        CurrentWFStageID: '',
        WFGroupID: '',
        WFComplete: false,
        ApprovalRequired: false,
        SubmittedBy: 'Timesheet',
        PBRateFrom: '',
        PBCurrencyCode: '',
        PBHours: 0,
        PBChargeRate: 0,
        PBChargeAmt: 0,
        DocPBChargeRate: 0,
        Rpt1PBChargeRate: 0,
        Rpt2PBChargeRate: 0,
        Rpt3PBChargeRate: 0,
        DocPBChargeAmt: 0,
        Rpt1PBChargeAmt: 0,
        Rpt2PBChargeAmt: 0,
        Rpt3PBChargeAmt: 0,
        Shift: 1,
        ActID: 0,
        DtailID: 0,
        ProjProcessed: false,
        AsOfDate: null,
        AsOfSeq: 0,
        JDFInputFiles: '',
        JDFNumberOfPages: '',
        BatchWasSaved: '',
        AssignToBatch: false,
        BatchComplete: false,
        BatchRequestMove: false,
        BatchPrint: false,
        BatchLaborHrs: 0,
        BatchPctOfTotHrs: 0,
        BatchQty: 0,
        BatchTotalExpectedHrs: 0,
        JDFOpCompleted: '',
        SysRevID: 1160103091,
        SysRowID: 'fe38b3e0-45fc-496b-8e7e-3f58854a302c',
        Downtime: false,
        RefJobNum: '',
        RefAssemblySeq: 0,
        RefOprSeq: 0,
        Imported: false,
        ImportDate: null,
        TimeAutoSubmit: false,
        BatchMode: false,
        BillServiceRate: 0,
        HCMPayHours: 0,
        AllowDirLbr: true,
        ApprovalPhaseID: '',
        ApprovalProjectDesc: '',
        ApprovalProjectID: '',
        ApprovedBy: '',
        ApprvrHasOpenTask: false,
        BaseCurrCodeDesc: '',
        BurdenCost: 40,
        CapabilityDescription: '',
        CapabilityID: '',
        ChargeRate: 0,
        ChargeRateSRC: '',
        ChgRateCurrDesc: '',
        CompleteFlag: false,
        DiscrepUOM: 'EA',
        DisLaborType: false,
        DisplayJob: 'L01094-L25',
        DisPrjRoleCd: false,
        DisTimeTypCd: true,
        DowntimeTotal: 0,
        DspChangeTime: '16:21',
        DspCreateTime: '16:21',
        DspTotHours: '',
        DtClockIn: null,
        DtClockOut: null,
        EfficiencyPercentage: 0,
        EmployeeName: '',
        EnableComplete: true,
        EnableCopy: true,
        EnableDiscrepQty: true,
        EnableInspection: false,
        EnableLaborQty: true,
        EnableNextOprSeq: false,
        EnablePrintTagsList: false,
        EnableRecall: false,
        EnableRecallAprv: false,
        EnableRequestMove: false,
        EnableResourceGrpID: false,
        EnableScrapQty: true,
        EnableSN: false,
        EnableSubmit: false,
        EndActivity: false,
        EnteredOnCurPlant: true,
        FSComplete: false,
        GLTranAmt: 0,
        GLTranDate: null,
        HasAccessToRow: true,
        HasComments: false,
        ISFixHourAndQtyOnly: false,
        JCSystReworkReasons: true,
        JCSystScrapReasons: false,
        JobOperComplete: false,
        JobType: 'Manufacture',
        JobTypeCode: 'MFG',
        LaborCost: 25.9,
        LaborUOM: 'EA',
        LbrDay: '',
        LbrMonth: '',
        LbrWeek: '',
        MES: false,
        MultipleEmployeesText: '',
        NewDifDateFlag: 0,
        NewPrjRoleCd: '',
        NewRoleCdDesc: '',
        NextAssemblySeq: 0,
        NextOperDesc: '',
        NextOprSeq: 0,
        NextResourceDesc: '',
        NonConfProcessed: false,
        NotSubmitted: true,
        OkToChangeResourceGrpID: false,
        PartDescription: '',
        PartNum: '',
        PBAllowModify: false,
        PendingApprovalBy: '',
        PhaseJobNum: '',
        PhaseOprSeq: 0,
        PrintNCTag: false,
        PrjUsedTran: '',
        ProdDesc: 'Production',
        ProjPhaseID: '',
        RequestMove: false,
        ResourceDesc: '',
        RoleCdDisplayAll: false,
        ScrapUOM: 'EA',
        SentFromMES: false,
        StartActivity: false,
        TimeDisableDelete: false,
        TimeDisableUpdate: false,
        TreeNodeImageName: 'Entered',
        UnapprovedFirstArt: false,
        WeekDisplayText: '11/26/2017 - 12/2/2017',
        ApprovalPhaseDesc: '',
        BitFlag: 0,
        DiscrpRsnDescription: '',
        EmpBasicLastName: 'Sheet',
        EmpBasicFirstName: 'Time',
        EmpBasicName: 'Time Sheet',
        ExpenseCodeDescription: 'Main',
        HCMIntregationHCMEnabled: false,
        HCMStatusStatus: '',
        IndirectDescription: '',
        JCDeptDescription: 'Electrical Production',
        JobAsmblDescription: 'Al Hab - Site Installation',
        MachineDescription: '',
        OpCodeOpDesc: 'Electrical Assembly',
        OpDescOpDesc: 'Electrical Assembly',
        PayMethodType: 0,
        PayMethodSummarizePerCustomer: false,
        PayMethodName: '',
        PhaseIDDescription: '',
        ProjectDescription: '',
        ResourceGrpDescription: 'Electrical Production',
        ResReasonDescription: '',
        ReWorkReasonDescription: '',
        RoleCdRoleDescription: '',
        ScrapReasonDescription: '',
        ShiftDescription: 'First Shift',
        TimeTypCdDescription: '',
        RowMod: '',
        Character01: '',
        EmpCostCenter_c: 'C29',
        Number01: 0,
        ShortChar01: '',
        TSheetsID_c: 0,
        UD_SysRevID: 'AAAAAEUlw3I='
      },
      {
        Company: '700',
        EmployeeNum: 'TS',
        LaborHedSeq: 715628,
        LaborDtlSeq: 2179556,
        LaborType: 'P',
        LaborTypePseudo: 'P',
        ReWork: false,
        ReworkReasonCode: '',
        JobNum: 'ICLDEL_W44Y16',
        AssemblySeq: 0,
        OprSeq: 20,
        JCDept: 'RGATMENG',
        ResourceGrpID: 'RGATMENG',
        OpCode: 'OPELEINT',
        LaborHrs: 1,
        BurdenHrs: 1,
        LaborQty: 0,
        ScrapQty: 0,
        ScrapReasonCode: '',
        SetupPctComplete: 0,
        Complete: false,
        IndirectCode: '',
        LaborNote: '',
        ExpenseCode: 'MAIN',
        LaborCollection: false,
        AppliedToSchedule: false,
        ClockInMInute: 33702240,
        ClockOutMinute: 33702780,
        ClockInDate: '2017-11-28T00:00:00',
        ClockinTime: 8,
        ClockOutTime: 17,
        ActiveTrans: false,
        OverRidePayRate: 0,
        LaborRate: 0,
        BurdenRate: 20,
        DspClockInTime: '08:00',
        DspClockOutTime: '17:00',
        ResourceID: '',
        OpComplete: false,
        EarnedHrs: 0,
        AddedOper: false,
        PayrollDate: '2017-11-28T00:00:00',
        PostedToGL: false,
        FiscalYear: 0,
        FiscalPeriod: 0,
        JournalNum: 0,
        GLTrans: true,
        JournalCode: '',
        InspectionPending: false,
        CallNum: 0,
        CallLine: 0,
        ServNum: 0,
        ServCode: '',
        ResReasonCode: '',
        WipPosted: false,
        DiscrepQty: 0,
        DiscrpRsnCode: '',
        ParentLaborDtlSeq: 0,
        LaborEntryMethod: 'T',
        FiscalYearSuffix: '',
        FiscalCalendarID: '',
        BFLaborReq: false,
        ABTUID: '',
        ProjectID: '',
        PhaseID: '',
        RoleCd: '',
        TimeTypCd: '',
        PBInvNum: 0,
        PMUID: 0,
        TaskSetID: '',
        ApprovedDate: null,
        ClaimRef: '',
        QuickEntryCode: '',
        TimeStatus: 'E',
        CreatedBy: 'Timesheet',
        CreateDate: '2017-11-29T00:00:00',
        CreateTime: 59004,
        ChangedBy: 'Timesheet',
        ChangeDate: '2017-11-29T00:00:00',
        ChangeTime: 59004,
        ActiveTaskID: '',
        LastTaskID: '',
        CreatedViaTEWeekView: false,
        CurrentWFStageID: '',
        WFGroupID: '',
        WFComplete: false,
        ApprovalRequired: false,
        SubmittedBy: '',
        PBRateFrom: '',
        PBCurrencyCode: '',
        PBHours: 0,
        PBChargeRate: 0,
        PBChargeAmt: 0,
        DocPBChargeRate: 0,
        Rpt1PBChargeRate: 0,
        Rpt2PBChargeRate: 0,
        Rpt3PBChargeRate: 0,
        DocPBChargeAmt: 0,
        Rpt1PBChargeAmt: 0,
        Rpt2PBChargeAmt: 0,
        Rpt3PBChargeAmt: 0,
        Shift: 1,
        ActID: 0,
        DtailID: 0,
        ProjProcessed: false,
        AsOfDate: null,
        AsOfSeq: 0,
        JDFInputFiles: '',
        JDFNumberOfPages: '',
        BatchWasSaved: '',
        AssignToBatch: false,
        BatchComplete: false,
        BatchRequestMove: false,
        BatchPrint: false,
        BatchLaborHrs: 0,
        BatchPctOfTotHrs: 0,
        BatchQty: 0,
        BatchTotalExpectedHrs: 0,
        JDFOpCompleted: '',
        SysRevID: 1160103096,
        SysRowID: 'fd081a58-65cc-4fd4-8dce-55e4d4e21628',
        Downtime: false,
        RefJobNum: '',
        RefAssemblySeq: 0,
        RefOprSeq: 0,
        Imported: false,
        ImportDate: null,
        TimeAutoSubmit: false,
        BatchMode: false,
        BillServiceRate: 0,
        HCMPayHours: 0,
        AllowDirLbr: true,
        ApprovalPhaseID: '',
        ApprovalProjectDesc: '',
        ApprovalProjectID: '',
        ApprovedBy: '',
        ApprvrHasOpenTask: false,
        BaseCurrCodeDesc: '',
        BurdenCost: 20,
        CapabilityDescription: '',
        CapabilityID: '',
        ChargeRate: 0,
        ChargeRateSRC: '',
        ChgRateCurrDesc: '',
        CompleteFlag: false,
        DiscrepUOM: 'EA',
        DisLaborType: false,
        DisplayJob: 'ICLDEL_W44Y16',
        DisPrjRoleCd: false,
        DisTimeTypCd: true,
        DowntimeTotal: 0,
        DspChangeTime: '16:23',
        DspCreateTime: '16:23',
        DspTotHours: '',
        DtClockIn: null,
        DtClockOut: null,
        EfficiencyPercentage: 0,
        EmployeeName: '',
        EnableComplete: true,
        EnableCopy: true,
        EnableDiscrepQty: true,
        EnableInspection: false,
        EnableLaborQty: true,
        EnableNextOprSeq: false,
        EnablePrintTagsList: false,
        EnableRecall: false,
        EnableRecallAprv: false,
        EnableRequestMove: false,
        EnableResourceGrpID: false,
        EnableScrapQty: true,
        EnableSN: false,
        EnableSubmit: false,
        EndActivity: false,
        EnteredOnCurPlant: true,
        FSComplete: false,
        GLTranAmt: 0,
        GLTranDate: null,
        HasAccessToRow: true,
        HasComments: false,
        ISFixHourAndQtyOnly: false,
        JCSystReworkReasons: true,
        JCSystScrapReasons: false,
        JobOperComplete: false,
        JobType: 'Manufacture',
        JobTypeCode: 'MFG',
        LaborCost: 12.95,
        LaborUOM: 'EA',
        LbrDay: '',
        LbrMonth: '',
        LbrWeek: '',
        MES: false,
        MultipleEmployeesText: '',
        NewDifDateFlag: 0,
        NewPrjRoleCd: '',
        NewRoleCdDesc: '',
        NextAssemblySeq: 0,
        NextOperDesc: '',
        NextOprSeq: 0,
        NextResourceDesc: '',
        NonConfProcessed: false,
        NotSubmitted: true,
        OkToChangeResourceGrpID: false,
        PartDescription: '',
        PartNum: '',
        PBAllowModify: false,
        PendingApprovalBy: '',
        PhaseJobNum: '',
        PhaseOprSeq: 0,
        PrintNCTag: false,
        PrjUsedTran: '',
        ProdDesc: 'Production',
        ProjPhaseID: '',
        RequestMove: false,
        ResourceDesc: '',
        RoleCdDisplayAll: false,
        ScrapUOM: 'EA',
        SentFromMES: false,
        StartActivity: false,
        TimeDisableDelete: false,
        TimeDisableUpdate: false,
        TreeNodeImageName: 'Entered',
        UnapprovedFirstArt: false,
        WeekDisplayText: '11/26/2017 - 12/2/2017',
        ApprovalPhaseDesc: '',
        BitFlag: 0,
        DiscrpRsnDescription: '',
        EmpBasicLastName: 'Sheet',
        EmpBasicFirstName: 'Time',
        EmpBasicName: 'Time Sheet',
        ExpenseCodeDescription: 'Main',
        HCMIntregationHCMEnabled: false,
        HCMStatusStatus: '',
        IndirectDescription: '',
        JCDeptDescription: 'Automation Engineering',
        JobAsmblDescription: 'Week 44 Interco Rechg to DEL',
        MachineDescription: '',
        OpCodeOpDesc: 'Electrical Site Install',
        OpDescOpDesc: 'Electrical Site Install',
        PayMethodType: 0,
        PayMethodSummarizePerCustomer: false,
        PayMethodName: '',
        PhaseIDDescription: '',
        ProjectDescription: '',
        ResourceGrpDescription: 'Automation Engineering',
        ResReasonDescription: '',
        ReWorkReasonDescription: '',
        RoleCdRoleDescription: '',
        ScrapReasonDescription: '',
        ShiftDescription: 'First Shift',
        TimeTypCdDescription: '',
        RowMod: '',
        Character01: '',
        EmpCostCenter_c: 'C29',
        Number01: 0,
        ShortChar01: '',
        TSheetsID_c: 0,
        UD_SysRevID: 'AAAAAEUlw9U='
      }
    ],
    LaborDtlComment: []
  },
  parameters: {
    morePages: false
  }
});
